services:
  - type: web
    name: vibe-backend
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DB_HOST
        fromDatabase:
          name: vibe-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true